// <auto-generated />
using System;
using CovidInfoWebService.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CovidInfoWebService.Migrations
{
    [DbContext(typeof(InfoCovidDbContext))]
    [Migration("20200510195837_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("CovidInfoWebService.Models.CasoCovid", b =>
                {
                    b.Property<int>("CasoCovidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocalizacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<char>("Sexo")
                        .HasColumnType("TEXT");

                    b.HasKey("CasoCovidId");

                    b.HasIndex("LocalizacionId");

                    b.ToTable("CasosCovid");
                });

            modelBuilder.Entity("CovidInfoWebService.Models.Localizacion", b =>
                {
                    b.Property<int>("LocalizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.HasKey("LocalizacionId");

                    b.ToTable("Localizacion");
                });

            modelBuilder.Entity("CovidInfoWebService.Models.CasoCovid", b =>
                {
                    b.HasOne("CovidInfoWebService.Models.Localizacion", "Localizacion")
                        .WithMany()
                        .HasForeignKey("LocalizacionId");
                });
#pragma warning restore 612, 618
        }
    }
}
